name: calendar_flutter
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: ^3.5.3

dependencies:
    flutter:
        sdk: flutter
    animated_toggle_switch: ^0.8.2
    keyboard_avoider: ^0.2.0
    firebase_core: ^3.5.0
    firebase_auth: ^5.3.0
    cloud_firestore: ^5.4.2
    mobx: ^2.3.3+2
    flutter_mobx: ^2.2.1+1
    build_runner: ^2.4.11
    mobx_codegen: ^2.6.1
    auto_size_text: ^3.0.0
    firebase_storage: ^12.3.1
    image_picker: ^1.1.2
    cached_network_image: ^3.4.1
    provider: ^6.1.2
    flutter_provider: ^2.1.0
    localstorage: ^5.0.0
    animations: ^2.0.11

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/pattern.jpg
